### ISSUE TITLE
Wish: some method to easily set the ServerName

### ISSUE THREAD

**Issue by JonBendtsen** [Dolibarr/dolibarr-docker#19]
Wish: some method to easily set the ServerName

```
root@livepod:/var/www/html# apache2ctl configtest
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.2.100. Set the 'ServerName' directive globally to suppress this message
Syntax OK
```

Here's an fix
```
root@livepod:/etc/apache2/conf-enabled# echo "ServerName dolibarr.example.com" > /etc/apache2/conf-enabled/servername.conf
root@livepod:/etc/apache2/conf-enabled# cat servername.conf 
ServerName dolibarr.example.com
root@livepod:/etc/apache2/conf-enabled# apache2ctl configtest
Syntax OK
```

How do we make it easy?

1. We could just mount the file in there when we create the container?
2. but it might be more efficient to have an environment variable which is then written into that file during upstart

**Comment by zunami** [comment]
@JonBendtsen thanks for this fix help.

**BUT** it doesn't help with the name resolution if the _http://localhost_ still appears for some links.

is there also a solution under docker where i can change the correct config file?

**Comment by creekorful** [comment]
@JonBendtsen Adding a variable (WEB_DOMAIN? Like we did WEB_PORT) and then using entrypoint to configurate Apache personally looks good to me.

One question tho : I am more of a NGINX guy so what does this ServerName config accomplish?

Cheers

**Comment by JonBendtsen** [comment]
> @JonBendtsen thanks for this fix help.
> 
> **BUT** it doesn't help with the name resolution if the **_http://localhost_** still appears for some links.
> 
> is there also a solution under docker where i can change the correct config file?

There probably is an option in Docker to mount an external configuration file for Apache at the correct location inside the container. I don't use Docker, so I wouldn't know the exact details.

Which URL's return http://localhost on your Dolibarr installation? and inside Dolibarr you can tell it which address it is running at. What have you written there?

**Comment by JonBendtsen** [comment]
> @JonBendtsen Adding a variable (WEB_DOMAIN? Like we did WEB_PORT) and then using entrypoint to configurate Apache personally looks good to me.
> 
> One question tho : I am more of a NGINX guy so what does this ServerName config accomplish?

At least it removes a log entry where apache says "hey I don't know who I am". Given that you are likely to only run Dolibarr on this apache installation, it might not matter super much - but what also happens is that Apache uses a different configuration for the log file which may not be what we want.

(why are there even several different log configurations inside the container? - probably because they come by default from the upstream image or with the default apache package).

**Comment by KsmoinO** [comment]
you can set the hostname of your web container to remove this warning.
Compose example
``` yaml
version: "3.0"
services:
  web:
    hostname: dolibarr.example.com
```

**Comment by eldy** [comment]
Doc to setup the hostname has been added the README.md file.
