### ISSUE TITLE
bug? dolibarr v20 does not disable PHP functions?

### ISSUE THREAD

**Issue by JonBendtsen** [Dolibarr/dolibarr-docker#9]
dolibarr v20 admin tolls, about security page says:

```
You should disable PHP functions:  dl,  apache_note,  apache_setenv,  show_source,  virtual
```

Shouldn't they be disabled?

**Comment by mathieupotier** [comment]
PR opened : https://github.com/Dolibarr/dolibarr-docker/pull/17
But you know that you can basically also contribute ? ^_^

**Comment by JonBendtsen** [comment]
> PR opened : #17 But you know that you can basically also contribute ? ^_^

yes I do know that, and I have contributed to Dolibarr itself. Right now my focus is on stop having backpain which turned out to be my home office chair :-o so I can't really sit down and fix stuff.

Besides that I'm also working on using the new functionality that v20 brings for my dance class registration system, amoung this the API enabling of notifications for thirdparties - something I contributed 😝

**Comment by mathieupotier** [comment]
No prob was just joking about it 'cause you have created a lot of issues in a short time laps ^_^
I wish you to get better soon, and be able to sit down again and fix / improve things again ^_^

Cheers

Anyway PR is opened and wait for maintenance team approval ...

**Comment by JonBendtsen** [comment]
> No prob was just joking about it 'cause you have created a lot of issues in a short time laps ^_^ I wish you to get better soon, and be able to sit down again and fix / improve things again ^_^

yes I know I have opened quite a few issues in a short time. The reason is that I have been waiting for v20 - to get some of the changes I made myself - so once I got it I installed it at my demo server and started exploring it - which revealed at least all the issues I've come up with.


> Anyway PR is opened and wait for maintenance team approval ...

Lovely :-)
